# Generated by Django 6.0.5 on 2026-05-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auditlog'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['timestamp'], name='tracker_aud_timesta_3542e0_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['object_id'], name='tracker_aud_object__1bd6e3_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['changed_by'], name='tracker_aud_changed_665e3c_idx'),
        ),
    ]
